version: '3.0'
services:
  redis:
    image: redis

    # networks:
    #   - back-end


  db:
    image: postgres:9.4
    environment: 
      POSTGRES_PASSWORD: postgres

   
    # networks:
    #   - back-end


  vote:
    image: voting-app

    ports:
      - 5000:80

    links:
      - redis

    # networks:
    #   - front-end
    #   - back-end


  result:
    image: result-app

    ports:
      - 5001:80

    links:
      - db

    # networks:
    #   - front-end
    #   - back-end

  worker:
    image: worker-app

    links:
      - redis
      - db

